import { FlatCompat } from "@eslint/eslintrc";
import baseConfig from "@inventra/eslint-config";

const compat = new FlatCompat({
  baseDirectory: import.meta.dirname,
});

const config = [
  ...baseConfig,
  // Only core-web-vitals — "next/typescript" would register its own
  // @typescript-eslint plugin instance and collide with the one
  // @inventra/eslint-config already sets up (and ours is stricter).
  ...compat.extends("next/core-web-vitals"),
  {
    // next-env.d.ts is autogenerated by Next and its triple-slash
    // references are the correct, required syntax for that file.
    ignores: [".next/**", "next-env.d.ts"],
  },
];

export default config;
